-- Pod 0 / S8 — Covariate balance check.  *** EXERCISE: finish this yourself ***
--
-- GOAL --------------------------------------------------------------------------
-- Produce one row per covariate f0..f11 with the standardized mean difference (SMD)
-- for TWO different splits, so you can read both of these off one table:
--
--   split A: treatment = 1  vs  treatment = 0
--            EXPECTED: |SMD| tiny  -> randomization worked
--
--   split B: exposure = 1   vs  exposure = 0   (within treatment = 1 only)
--            EXPECTED: |SMD| large -> exposure is selected, not randomized
--
-- SMD is the right statistic here instead of a t-test: with n = 14M, a t-test calls
-- every trivial difference significant, so a p-value carries no information. SMD is a
-- dimensionless effect size and does not inflate with n. Rule of thumb: |SMD| < 0.1 is
-- balanced, < 0.01 is very clean.
--
--     SMD = (mean_A - mean_B) / sqrt( (var_A + var_B) / 2 )
--
-- WHAT YOU NEED ----------------------------------------------------------------
--   avg(f0), var_samp(f0)  computed separately for each side of each split
--   the result shaped LONG (one row per covariate), not WIDE (one column per covariate)
--
-- HINTS -------------------------------------------------------------------------
--   * conditional aggregation:  avg(CASE WHEN treatment = 1 THEN f0 END)
--     (CASE returns NULL otherwise, and avg() skips NULLs -- here that is exactly
--     what you want, but remember it is also pitfall #5 in the playbook)
--   * to go from wide to long, either UNION ALL twelve small SELECTs, or compute a
--     wide row first and then UNPIVOT it:
--         SELECT * FROM (<wide query>) UNPIVOT (value FOR covariate IN (f0, f1, ...))
--   * var_samp(x) is the sample variance in DuckDB
--   * write it incrementally: get f0 alone working for split A, then add split B,
--     then generalize to all twelve columns. Never try to write the final form first.
--
-- TARGET OUTPUT ----------------------------------------------------------------
--   covariate | smd_treat_vs_control | smd_exposed_vs_unexposed
--   f0        | 0.0003               | 0.41
--   f1        | ...                  | ...
--
-- QUESTIONS TO ANSWER ONCE IT RUNS ---------------------------------------------
--   1. Are all twelve |smd_treat_vs_control| below 0.01? If one is not, what would
--      you check before concluding the randomization was broken?
--   2. Which covariates are most imbalanced between exposed and unexposed? Given that
--      f0..f11 are randomly projected and therefore uninterpretable, what can you
--      still conclude from the *pattern* of imbalance?
--   3. How would you use these covariates to reduce the variance of the ITT estimate?

-- YOUR QUERY BELOW
SELECT 'TODO: replace me' AS covariate
