"""Generate sql/04_covariate_balance.sql.

Twelve covariates x two splits x two statistics is 96 near-identical aggregate
expressions. Hand-writing them invites typos that are invisible in review, so the file is
generated and the generator is what gets reviewed.

The output deliberately uses only CASE aggregation, var_samp and UNION ALL, all of which
parse on both DuckDB and Trino. DuckDB's UNPIVOT would be shorter and is not portable.

    python scripts/gen_balance_sql.py
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "sql" / "04_covariate_balance.sql"
TABLE = "bronze.criteo_uplift"
COVARIATES = [f"f{i}" for i in range(12)]

# short key -> predicate selecting that group
GROUPS = {
    "t": "treatment = 1",
    "c": "treatment = 0",
    "e": "treatment = 1 AND exposure = 1",
    "u": "treatment = 1 AND exposure = 0",
}

HEADER = """-- Covariate balance: does randomization hold, and is delivery selective?
--
-- Standardized mean difference (SMD) for two different splits of the same covariates:
--
--   smd_assignment : treatment = 1  vs  treatment = 0
--                    randomization implies these are near zero
--   smd_exposure   : exposed       vs  not exposed, within the treated arm
--                    delivery is an auction outcome, so these are expected to be large
--
--       SMD = (mean_A - mean_B) / sqrt((var_A + var_B) / 2)
--
-- SMD rather than a t-test: at n = 14M every trivial difference is "significant", so a
-- p-value carries no information. SMD is dimensionless and does not inflate with n.
-- Conventional reading: |SMD| < 0.10 balanced, < 0.01 very clean.
--
-- Generated by scripts/gen_balance_sql.py -- edit the generator, not this file.
-- Portable across DuckDB and Trino/Athena: CASE aggregation, var_samp, UNION ALL only.

WITH stats AS (
    SELECT
"""


def build() -> str:
    aggregates: list[str] = []
    for col in COVARIATES:
        for key, predicate in GROUPS.items():
            aggregates.append(
                f"        avg(CASE WHEN {predicate} THEN {col} END)      AS {col}_{key}_mean,"
            )
            aggregates.append(
                f"        var_samp(CASE WHEN {predicate} THEN {col} END) AS {col}_{key}_var,"
            )
    aggregates[-1] = aggregates[-1].rstrip(",")

    blocks = [
        f"    SELECT '{col}' AS covariate,\n"
        f"           ({col}_t_mean - {col}_c_mean) / sqrt(({col}_t_var + {col}_c_var) / 2.0) AS smd_assignment,\n"
        f"           ({col}_e_mean - {col}_u_mean) / sqrt(({col}_e_var + {col}_u_var) / 2.0) AS smd_exposure\n"
        f"    FROM stats"
        for col in COVARIATES
    ]

    return (
        HEADER
        + "\n".join(aggregates)
        + f"\n    FROM {TABLE}\n)\n"
        + "\nUNION ALL\n".join(blocks)
        + "\nORDER BY covariate\n"
    )


if __name__ == "__main__":
    OUT.write_text(build())
    print(f"wrote {OUT} ({len(build().splitlines())} lines)")
