-- Covariate balance: does randomization hold, and is delivery selective?
--
-- Standardized mean difference (SMD) for two different splits of the same covariates:
--
--   smd_assignment : treatment = 1  vs  treatment = 0
--                    randomization implies these are near zero
--   smd_exposure   : exposed       vs  not exposed, within the treated arm
--                    delivery is an auction outcome, so these are expected to be large
--
--       SMD = (mean_A - mean_B) / sqrt((var_A + var_B) / 2)
--
-- SMD rather than a t-test: at n = 14M every trivial difference is "significant", so a
-- p-value carries no information. SMD is dimensionless and does not inflate with n.
-- Conventional reading: |SMD| < 0.10 balanced, < 0.01 very clean.
--
-- Generated by scripts/gen_balance_sql.py -- edit the generator, not this file.
-- Portable across DuckDB and Trino/Athena: CASE aggregation, var_samp, UNION ALL only.

WITH stats AS (
    SELECT
        avg(CASE WHEN treatment = 1 THEN f0 END)      AS f0_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f0 END) AS f0_t_var,
        avg(CASE WHEN treatment = 0 THEN f0 END)      AS f0_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f0 END) AS f0_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f0 END)      AS f0_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f0 END) AS f0_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f0 END)      AS f0_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f0 END) AS f0_u_var,
        avg(CASE WHEN treatment = 1 THEN f1 END)      AS f1_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f1 END) AS f1_t_var,
        avg(CASE WHEN treatment = 0 THEN f1 END)      AS f1_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f1 END) AS f1_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f1 END)      AS f1_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f1 END) AS f1_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f1 END)      AS f1_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f1 END) AS f1_u_var,
        avg(CASE WHEN treatment = 1 THEN f2 END)      AS f2_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f2 END) AS f2_t_var,
        avg(CASE WHEN treatment = 0 THEN f2 END)      AS f2_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f2 END) AS f2_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f2 END)      AS f2_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f2 END) AS f2_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f2 END)      AS f2_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f2 END) AS f2_u_var,
        avg(CASE WHEN treatment = 1 THEN f3 END)      AS f3_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f3 END) AS f3_t_var,
        avg(CASE WHEN treatment = 0 THEN f3 END)      AS f3_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f3 END) AS f3_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f3 END)      AS f3_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f3 END) AS f3_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f3 END)      AS f3_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f3 END) AS f3_u_var,
        avg(CASE WHEN treatment = 1 THEN f4 END)      AS f4_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f4 END) AS f4_t_var,
        avg(CASE WHEN treatment = 0 THEN f4 END)      AS f4_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f4 END) AS f4_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f4 END)      AS f4_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f4 END) AS f4_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f4 END)      AS f4_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f4 END) AS f4_u_var,
        avg(CASE WHEN treatment = 1 THEN f5 END)      AS f5_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f5 END) AS f5_t_var,
        avg(CASE WHEN treatment = 0 THEN f5 END)      AS f5_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f5 END) AS f5_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f5 END)      AS f5_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f5 END) AS f5_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f5 END)      AS f5_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f5 END) AS f5_u_var,
        avg(CASE WHEN treatment = 1 THEN f6 END)      AS f6_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f6 END) AS f6_t_var,
        avg(CASE WHEN treatment = 0 THEN f6 END)      AS f6_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f6 END) AS f6_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f6 END)      AS f6_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f6 END) AS f6_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f6 END)      AS f6_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f6 END) AS f6_u_var,
        avg(CASE WHEN treatment = 1 THEN f7 END)      AS f7_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f7 END) AS f7_t_var,
        avg(CASE WHEN treatment = 0 THEN f7 END)      AS f7_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f7 END) AS f7_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f7 END)      AS f7_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f7 END) AS f7_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f7 END)      AS f7_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f7 END) AS f7_u_var,
        avg(CASE WHEN treatment = 1 THEN f8 END)      AS f8_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f8 END) AS f8_t_var,
        avg(CASE WHEN treatment = 0 THEN f8 END)      AS f8_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f8 END) AS f8_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f8 END)      AS f8_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f8 END) AS f8_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f8 END)      AS f8_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f8 END) AS f8_u_var,
        avg(CASE WHEN treatment = 1 THEN f9 END)      AS f9_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f9 END) AS f9_t_var,
        avg(CASE WHEN treatment = 0 THEN f9 END)      AS f9_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f9 END) AS f9_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f9 END)      AS f9_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f9 END) AS f9_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f9 END)      AS f9_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f9 END) AS f9_u_var,
        avg(CASE WHEN treatment = 1 THEN f10 END)      AS f10_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f10 END) AS f10_t_var,
        avg(CASE WHEN treatment = 0 THEN f10 END)      AS f10_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f10 END) AS f10_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f10 END)      AS f10_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f10 END) AS f10_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f10 END)      AS f10_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f10 END) AS f10_u_var,
        avg(CASE WHEN treatment = 1 THEN f11 END)      AS f11_t_mean,
        var_samp(CASE WHEN treatment = 1 THEN f11 END) AS f11_t_var,
        avg(CASE WHEN treatment = 0 THEN f11 END)      AS f11_c_mean,
        var_samp(CASE WHEN treatment = 0 THEN f11 END) AS f11_c_var,
        avg(CASE WHEN treatment = 1 AND exposure = 1 THEN f11 END)      AS f11_e_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 1 THEN f11 END) AS f11_e_var,
        avg(CASE WHEN treatment = 1 AND exposure = 0 THEN f11 END)      AS f11_u_mean,
        var_samp(CASE WHEN treatment = 1 AND exposure = 0 THEN f11 END) AS f11_u_var
    FROM bronze.criteo_uplift
)
    SELECT 'f0' AS covariate,
           (f0_t_mean - f0_c_mean) / sqrt((f0_t_var + f0_c_var) / 2.0) AS smd_assignment,
           (f0_e_mean - f0_u_mean) / sqrt((f0_e_var + f0_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f1' AS covariate,
           (f1_t_mean - f1_c_mean) / sqrt((f1_t_var + f1_c_var) / 2.0) AS smd_assignment,
           (f1_e_mean - f1_u_mean) / sqrt((f1_e_var + f1_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f2' AS covariate,
           (f2_t_mean - f2_c_mean) / sqrt((f2_t_var + f2_c_var) / 2.0) AS smd_assignment,
           (f2_e_mean - f2_u_mean) / sqrt((f2_e_var + f2_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f3' AS covariate,
           (f3_t_mean - f3_c_mean) / sqrt((f3_t_var + f3_c_var) / 2.0) AS smd_assignment,
           (f3_e_mean - f3_u_mean) / sqrt((f3_e_var + f3_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f4' AS covariate,
           (f4_t_mean - f4_c_mean) / sqrt((f4_t_var + f4_c_var) / 2.0) AS smd_assignment,
           (f4_e_mean - f4_u_mean) / sqrt((f4_e_var + f4_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f5' AS covariate,
           (f5_t_mean - f5_c_mean) / sqrt((f5_t_var + f5_c_var) / 2.0) AS smd_assignment,
           (f5_e_mean - f5_u_mean) / sqrt((f5_e_var + f5_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f6' AS covariate,
           (f6_t_mean - f6_c_mean) / sqrt((f6_t_var + f6_c_var) / 2.0) AS smd_assignment,
           (f6_e_mean - f6_u_mean) / sqrt((f6_e_var + f6_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f7' AS covariate,
           (f7_t_mean - f7_c_mean) / sqrt((f7_t_var + f7_c_var) / 2.0) AS smd_assignment,
           (f7_e_mean - f7_u_mean) / sqrt((f7_e_var + f7_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f8' AS covariate,
           (f8_t_mean - f8_c_mean) / sqrt((f8_t_var + f8_c_var) / 2.0) AS smd_assignment,
           (f8_e_mean - f8_u_mean) / sqrt((f8_e_var + f8_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f9' AS covariate,
           (f9_t_mean - f9_c_mean) / sqrt((f9_t_var + f9_c_var) / 2.0) AS smd_assignment,
           (f9_e_mean - f9_u_mean) / sqrt((f9_e_var + f9_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f10' AS covariate,
           (f10_t_mean - f10_c_mean) / sqrt((f10_t_var + f10_c_var) / 2.0) AS smd_assignment,
           (f10_e_mean - f10_u_mean) / sqrt((f10_e_var + f10_u_var) / 2.0) AS smd_exposure
    FROM stats
UNION ALL
    SELECT 'f11' AS covariate,
           (f11_t_mean - f11_c_mean) / sqrt((f11_t_var + f11_c_var) / 2.0) AS smd_assignment,
           (f11_e_mean - f11_u_mean) / sqrt((f11_e_var + f11_u_var) / 2.0) AS smd_exposure
    FROM stats
ORDER BY covariate
